# Generated by Django 5.0.2 on 2024-02-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEcommerce', '0009_alter_itemcarrito_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
