# Generated by Django 5.0.1 on 2024-03-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEcommerce', '0013_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='items',
            field=models.ManyToManyField(related_name='carrito_items', to='appEcommerce.itemcarrito'),
        ),
    ]
