# Generated by Django 5.0.2 on 2024-03-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEcommerce', '0014_alter_carrito_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='items',
            field=models.ManyToManyField(to='appEcommerce.itemcarrito'),
        ),
    ]
