# Generated by Django 5.0.2 on 2024-06-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEcommerce', '0017_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(to='appEcommerce.categorias'),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(choices=[('Blanco', 'Blanco'), ('Negro', 'Negro'), ('Naranja', 'Naranja'), ('Azul', 'Azul'), ('Amarillo', 'Amarillo'), ('Cafe', 'Cafe'), ('Rojo', 'Rojo')], default='Blanco', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('XS', 'Extra Pequeña'), ('S', 'Pequeña'), ('M', 'Mediana'), ('L', 'Grande'), ('XL', 'Extra Grande')], default='S', max_length=50),
        ),
    ]
